service: notification-service

plugins:
  #- serverless-bundle
  - serverless-pseudo-parameters



provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256  
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - ses:SendEmail
      Resource: arn:aws:ses:*
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
      Resource: ${self:custom.mailQueue.arn}
      
    
            
resources:
  Resources:
    MailQueue:
      Type: AWS::SQS::Queue
      Properties:
          QueueName: ${self:custom.mailQueue.name}

  Outputs:
      MailQueueArn:
        Value: ${self:custom.mailQueue.arn}
        Export:
          Name: ${self:custom.mailQueue.name}-Arn
      MailQueueUrl:
        Value: ${self:custom.mailQueue.arn}
        Export:
          Name: ${self:custom.mailQueue.name}-Url 
  

    
      
functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:MailQueue-${self:provider.stage}  
          batchSize: 1
    # events:
    #   - sqs:
    #       arn: ${self:custom.mailQueue.arn}  
    #       batchSize: 1
          
         

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue 
  bundle:
    linting: false